sudo: required
service:
  - docker

before_install:
  - docker build -t ipuskaric12/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ipuskaric12/react-test npm test -- --coverage

after_success:
  - docker build -t ipuskaric12/multi-client ./client
  - docker build -t ipuskaric12/multi-nginx ./nginx
  - docker build -t ipuskaric12/multi-server ./server
  - docker build -t ipuskaric12/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 

  # Push those images to docker hub
  - docker push ipuskaric12/multi-client
  - docker push ipuskaric12/multi-nginx 
  - docker push ipuskaric12/multi-server
  - docker push ipuskaric12/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-938318033206
  bucket_path: docker-multi
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master